- name: Setup MSVC environment (Windows)
  if: runner.os == 'Windows'
  uses: ilammy/msvc-dev-cmd@v1

- name: Add NASM to PATH (Windows)
  if: runner.os == 'Windows'
  shell: bash
  run: echo C:/Program Files/NASM >> $GITHUB_PATH

- name: Install meson and pkg-config (Windows)
  if: runner.os == 'Windows'
  shell: bash
  run: |
    pip install meson
    choco install pkgconfiglite --yes

- name: Force MSVC compiler for meson (Windows)
  if: runner.os == 'Windows'
  shell: bash
  run: |
    echo "CC=cl" >> $GITHUB_ENV
    echo "CXX=cl" >> $GITHUB_ENV
    echo "_CL_=/MT" >> $GITHUB_ENV

- name: Set dav1d build-from-source flag
  shell: bash
  run: echo "SYSTEM_DEPS_DAV1D_BUILD_INTERNAL=always" >> $GITHUB_ENV
